### PR TITLE
fix(REACH-827): Add minimum wait time before closing modal

### PR DESCRIPTION
**Pull request by mathio**
When "autoClose" option is enabled wait minimum of 500ms to make sure all calls inside typeform are completed.

### CODE REVIEW

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `ca16975b5f3aaf6647fafa630054356f91e3f953` [here](https://embed.typeform.com/ca16975b5f3aaf6647fafa630054356f91e3f953/embed.js).

**Comment by mathio** [comment]
Cypress tests fail:

# functional: https://github.com/Typeform/embed/actions/runs/6313342316/job/17215551392
```
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was 44465.

Error: connect ECONNREFUSED 127.0.0.1:44465
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1[161](https://github.com/Typeform/embed/actions/runs/6313342316/job/17215551392#step:7:162):16)
```

# visual: https://github.com/Typeform/embed/actions/runs/6313342329/job/17215550420
```
read ECONNRESET
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:220:20)
```

Trying to run tests in default browser (Electron) as it seems to work there.

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `cc4da82e0fc13f4a1fb2f115bdf4beef70644f59` [here](https://embed.typeform.com/cc4da82e0fc13f4a1fb2f115bdf4beef70644f59/embed.js).

**Review by mumpo — APPROVED** [review]

**Pull request merged**
