### PR TITLE
PI-89 Add shareGoogleAnalyticsInstance option feature

### PR DESCRIPTION
**Pull request by supertinou**
# Motivation

Support the improvement to the Google Analytics Integration so that the Google analytics user session on the website where the Typeform is embedded is share to Typeform and even beyond and so that as the owner of the website I can get the accurate full view of the experience of the user and can get to improve it.

This specific feature is part of the bigger epic: https://jira.typeform.tf/browse/PI-88

# Under the hood

The changes allow you to specify a ```shareGoogleAnalyticsInstance```  option in the embed
and this had the effect to pass in a ```shareGoogleAnalyticsInstance``` parameter to the Typeform URL and to, if there is Google analytics in the page of the embed to pass a ```ga-client-id``` parameter via ```postMessage``` as soon as the google Analytics parameter Id is available.

# How to use the feature.

1) Enable the Google analytics integration

2) Enable the ```shareGoogleAnalyticsInstance``` in the embed:

In an HTML snippet using the embed:

```html
<div
      class="typeform-widget"
      data-url="mytypeformURL"
      data-share-google-analytics-instance
    ></div>
<script type="text/javascript" src="https://embed.typeform.com/embed.js"></script>
```

Using the API: 

```js

const embedElement = document.querySelector('.js-typeform-embed')

typeformEmbed.makeWidget(
  embedElement,
  'https://admin.typeform.com/to/PlBzgL',
  {
    buttonText: "Answer this!",
    shareGoogleAnalyticsInstance
  }
)
```

# JIRA: https://jira.typeform.tf/browse/PI-89

# Test plan

-  Unit tests to check that the embedded html snippet parse properly the `data-share-google-analytics-instance` parameter to the widget and popup api
- E2E test to chack that, when the ```shareGoogleAnalytics``` option is enabled, the ```share-ga-instance``` parameter is added to the Typeform URL and that the ```ga-client-id``` of the website google instance is transfered via ```postMessage``` to the Typeform.

### CODE REVIEW

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/398ceff5025e8c707967f2addbda1c8bf7d6b062/embed.js

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/5a6421fdba9cce7e478f3123a79a43769ad20d58/embed.js

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/36ca966c021cf2c325d4bc34fdb62e4ce0681869/embed.js

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/0df06be703d3935c02c68344729c5c062957955c/embed.js

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/d0ebaeea61aff5c2694d7c0864affa1965865b39/embed.js

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/048f85493b6199941b99ec45be6284785655e9d7/embed.js

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/3c5140416c39f22c9f980c048190c01dbf4505fb/embed.js

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/4b3a5cc8eefc9134754c9de18696091f5f1f17c4/embed.js

**Comment by mathio** [comment]
Feel free to reopen this if you need it again.

**Pull request closed without merging**
