### PR TITLE
feat(TU-8855): Do not auto-open modal if there already is a modal open

### PR DESCRIPTION
**Pull request by mathio**
Option `respectOpenModals` will prevent modal from opening when the auto-open condition is triggered if there already is a modal open:
- `all` - with any typeform
- `same` - with the same typeform

---

Includes a fix for `preventReOpenWhenClose` from https://github.com/Typeform/embed/pull/639 (ticket TU-8691).

### CODE REVIEW

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `f8393aa35c63a037fa784239b4ee3b8f6d9ce2ff` [here](https://embed.typeform.com/f8393aa35c63a037fa784239b4ee3b8f6d9ce2ff/embed.js).

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `757a5e0e0d484ebc4d735991851fd89d427851a8` [here](https://embed.typeform.com/757a5e0e0d484ebc4d735991851fd89d427851a8/embed.js).

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `a2ce5dbc0d68193d1b650da75aa559c0229df9d8` [here](https://embed.typeform.com/a2ce5dbc0d68193d1b650da75aa559c0229df9d8/embed.js).

**Review by Thr44 — APPROVED** [review]

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `9921968f643bebeea08c7a4a4f780f9e0b4e2386` [here](https://embed.typeform.com/9921968f643bebeea08c7a4a4f780f9e0b4e2386/embed.js).

**Pull request merged**
