### PR TITLE
fix(REACH-913): Apply min height to the widget iframe

### PR DESCRIPTION
**Pull request by gierlas**
What
We're moving the widget size style to widget options to be compatible with other widgets.

### CODE REVIEW

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `12d7214eddf1b75a96f6d959e608b0e0f7cfac66` [here](https://embed.typeform.com/12d7214eddf1b75a96f6d959e608b0e0f7cfac66/embed.js).

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `0bc86baef2f60e25a8eff2e2f798b38ba019b1e3` [here](https://embed.typeform.com/0bc86baef2f60e25a8eff2e2f798b38ba019b1e3/embed.js).

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `8f8a436dd74b1924f07c4b143b826b4bde8f1269` [here](https://embed.typeform.com/8f8a436dd74b1924f07c4b143b826b4bde8f1269/embed.js).

**Review by mathio — APPROVED** [review]

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `5278a88e1a0f78a4343ead5e5c14e086c1cead46` [here](https://embed.typeform.com/5278a88e1a0f78a4343ead5e5c14e086c1cead46/embed.js).

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `3862282fbc3a252226f83161e57c5bb0dd6a5ec2` [here](https://embed.typeform.com/3862282fbc3a252226f83161e57c5bb0dd6a5ec2/embed.js).

**Review by mathio — APPROVED** [review]
Noyce 👍

**Pull request merged**
