### PR TITLE
chore(DIST-144): Update Travis npm release config

### PR DESCRIPTION
**Pull request by mathio**
Docs for semantic release say it should be configurable via `release` prop in package.json but it does not work. Passing the argument to the command directly seems to work.

### CODE REVIEW

**Comment by prilutskiy** [comment]
How about introducing a [`.releaserc`](https://semantic-release.gitbook.io/semantic-release/usage/configuration#configuration-file) file for keeping the semantic-release configuration in it? It would result in a cleaner `package.json`

**Comment by mathio** [comment]
@prilutskiy I can try that. However for some reason the config in `package.json` did not work 🤷‍♂️

**Comment by mathio** [comment]
For some reason the `semantic-release` is not reading the config from a file (neither package.json nor .releaserc), it needs to be passed directly via command line option.

**Comment by prilutskiy** [comment]
@mathio it's a pity to hear that. Seems like they have a bug, because I'm pretty sure I used to get such setup working :)
Nevertheless - approved.

**Pull request merged**
