### PR TITLE
chore(DIST-228): Fix functional tests and remove hard wait times

### PR DESCRIPTION
**Pull request by mathio**
Tests click around very fast and `handleLoad()` throws errors, this fixes it. 
Move all widget tests into single file to speed up functional tests run time. 
Add Eslint support for Cypress.

---

The issue is resolved, [last 5 runs passed](https://travis-ci.com/github/Typeform/embed/pull_requests) (out of 27 total 🤣). Tests run on average ~30 seconds faster thanks to multiple optimizations (moved all widget tests to single file, removed [anti-pattern hardcoded waiting times](https://docs.cypress.io/api/commands/wait.html#Examples)).

### CODE REVIEW

**Comment by prilutskiy** [comment]
Embed script preview available: https://embed.typeform.com/365c79744425d4b75b4f0bc2d72e5d4fe4bb8940/embed.js

**Comment by travis-tf** [comment]
Embed script preview available: https://embed.typeform.com/d861f760eda23796e19415084af074308ec19bc8/embed.js

**Comment by travis-tf** [comment]
Embed script preview available: https://embed.typeform.com/2c845b66f1c55439650d622730c7261bbe22879c/embed.js

**Comment by travis-tf** [comment]
Embed script preview available: https://embed.typeform.com/882845dac18645dc32a16baf0bb84f61f36a301b/embed.js

**Comment by travis-tf** [comment]
Embed script preview available: https://embed.typeform.com/1896f4b33f73b8eb2d9d7d70791928d62108dd2e/embed.js

**Comment by travis-tf** [comment]
Embed script preview available: https://embed.typeform.com/cf71200d2cf5af42c8a1042316c03d453cbb0494/embed.js

**Comment by travis-tf** [comment]
Embed script preview available: https://embed.typeform.com/4d97badddddd020903f27a9a3e017016aabd1087/embed.js

**Comment by travis-tf** [comment]
Embed script preview available: https://embed.typeform.com/495837969df38c58b63e1e87b7b2a740ff587951/embed.js

**Pull request merged**
