### PR TITLE
fix(DIST-548): Make side tab button reponsive to text

### PR DESCRIPTION
**Pull request by antoniofull**
- [ ] Explain the **motivation** for making this change.
- [ ] Provide a solid **test plan** for your changes.
- [ ]  Link to the issue - if any [DIST-548](https://jira.typeform.tf/browse/DIST-548)

### CODE REVIEW

**Comment by mathio** [comment]
Why so many indentation changes? Can you please revert it, its hard to review.

**Comment by antoniofull** [comment]
> Why so many indentation changes? Can you please revert it, its hard to review.

I formatted the code properly as it was not. Will revert those changes

**Comment by antoniofull** [comment]
Hey @mathio should be better now, sorry for the confusion 😄

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/cf427a651511971f6c3188a9f4fb66f05b0c0cac/embed.js

**Review by mathio — APPROVED** [review]

**Pull request merged**
