### PR TITLE
chore(REACH-826): Update React lib README

### PR DESCRIPTION
**Pull request by mathio**

### CODE REVIEW

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `710dbaded0ec30c6f0d56ba3797ab0e5f2b56eac` [here](https://embed.typeform.com/710dbaded0ec30c6f0d56ba3797ab0e5f2b56eac/embed.js).

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `16cd68532141a0632601f97b4198e06ac5f4d9fd` [here](https://embed.typeform.com/16cd68532141a0632601f97b4198e06ac5f4d9fd/embed.js).

**Review by mumpo — APPROVED** [review]

**Comment by mathio** [comment]
Failing tests not related to changes nor the repo code.

**Pull request merged**
