### PR TITLE
feat(DIST-1217): Add tracking as url option

### PR DESCRIPTION
**Pull request by scarciofolomarco**

### CODE REVIEW

**Comment by maxprilutskiy** [comment]
Do we want to add anything about this flag to the README?

**Review by mathio — CHANGES_REQUESTED** [review]
Add tests please

**Comment by mathio** [comment]
> Do we want to add anything about this flag to the README?

Good point  ☝️

**Review by mathio — APPROVED** [review]

**Review by antoniofull — APPROVED** [review]

**Pull request merged**
