### PR TITLE
feat(TYP-6029): Change CSS classnames prefixes

### PR DESCRIPTION
**Pull request by mathio**
This prevents conflicts with old embed SDK lib (when both libs are in one page).

### CODE REVIEW

**Review by scarciofolomarco — APPROVED** [review]

**Comment by maxprilutskiy** [comment]
Love the idea! Why `v1` though, and not just `tf` ?

**Review by maxprilutskiy — APPROVED** [review]

**Comment by mathio** [comment]
If we have a new version with breaking changes in future we can rename the class to v2 and forget about possible conflicts. Credit to @scarciofolomarco for the idea!

**Pull request merged**
