### PR TITLE
feat(DIST-301): Add functional tests for behavioral triggers from DIST-193

### PR DESCRIPTION
**Pull request by mathio**
Test embeds created via embed code and API

### CODE REVIEW

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/2ea88be0037bed1fd207245ceb0d08a16e01b320/embed.js

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/874dbb7c4b8b65627fb1e8a4042fce7c07102719/embed.js

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/54679b6abbb57f78d8bd06eb079c397694b5e9cf/embed.js

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/52072fe635b7bf124332799637b6965fb6979dab/embed.js

**Comment by mathio** [comment]
[Cypress supports many browsers.](https://docs.cypress.io/guides/guides/launching-browsers.html#Browsers) However I dont see any benefit from that since all other supported browsers are chrome-based. Safari and IE are not supported by Cypress and we would not be able to run those in Travis anyway (it runs linux container).

As for different resolutions, we run with desktop and mobile screen sizes which I think is sufficient.

**Pull request merged**
