### PR TITLE
feat(TU-17542): Update docs on sandbox mode

### LINKED ISSUE #662: Request ID should be sometimes undefined
The `event` argument type passed to the `onSubmit` callback (and probably others, I didn't check) can be `undefined` when sandbox mode is enabled. However, the type definition says it's always a string.

Can be seen when using React

```jsx
<Widget 
  onSubmit={(event) => console.log(typeof event.responseId)}
  sandboxMode={true}
/>
```

`event.responseId` is `undefined` when sandbox mode is enabled, but the type definition is `string`, not `string | undefined`.

### The fix

Update [this line](https://github.com/Typeform/embed/blob/4c9aea13a526561886e4a718517ea462d07f0143/packages/embed/src/base/actionable-options.ts#L32C35-L32C49) to be

```typescript
  onSubmit?: (event: WithFormId & Partial<WithResponseId>) => void
```

However, that may indicate `responseId` is missing, not set to `undefined`, so you could also update `WithResponseId` to be `{ responseId: string | undefined }`, but I'm not sure where else that type is used and what the repercussion is.

### PR DESCRIPTION
**Pull request by mathio**
Resolves #662

### CODE REVIEW

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `ae1dff159e1b2ac9ffafcbf9f4e454c37abb9401` [here](https://embed.typeform.com/ae1dff159e1b2ac9ffafcbf9f4e454c37abb9401/embed.js).

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `4b66c2d79fe57fa0436ba5dad6a6bb3bc9738599` [here](https://embed.typeform.com/4b66c2d79fe57fa0436ba5dad6a6bb3bc9738599/embed.js).

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `26212523ea374c97f99f61a1ca91c3fd70f4778e` [here](https://embed.typeform.com/26212523ea374c97f99f61a1ca91c3fd70f4778e/embed.js).

**Review by leandro-serafim — APPROVED** [review]

**Pull request merged**
