### PR TITLE
perf: Move react, react-dom to peer deps

### PR DESCRIPTION
**Pull request by osdiab**
- [x] Explain the **motivation** for making this change.

react and react-dom shouldn't be pinned so i dont need to install multiple versions of react to use this package

- [x] Provide a solid **test plan** for your changes.

tests ran, just make sure it's still loading as you expect.

- [x]  Link to the issue - if any #24

this doesn't close that issue, it's just a small part of it.

### CODE REVIEW

**Review by prilutskiy — APPROVED** [review]
Great job!

**Comment by osdiab** [comment]
That was dev dependencies, you need it there because the tests depend on react being present.

**Comment by mathio** [comment]
You are correct. But if we keep it as dev dep it is included in the final bundle:
Screenshot 2020-10-28 at 12 37 19

A sample nextjs app would I am testing this in still has 2 copies of react:
Screenshot 2020-10-28 at 12 37 19

Maybe there is something wrong with our build process 🤔

**Comment by mathio** [comment]
I checked again and it looks like I was not installing it correctly. Your PR looks good as is, I removed my commit.

Lets merge it!

**Comment by mathio** [comment]
Sorry for the confusion. The change was released and works as expected. Thank you for the PR!

**Pull request merged**
