### PR TITLE
fix(TYP-6447): Slider close button and border radius on mobile

### PR DESCRIPTION
**Pull request by mathio**

### CODE REVIEW

**Review by antoniofull — COMMENTED** [review]
All those numbers in css are multiple of 4, wouldn't be more clear to have them in a calc function so that if we have to come back to it, we modify it once?

**Comment by mathio** [comment]
@antoniofull can you show an example of what you mean please?

**Comment by antoniofull** [comment]
> @antoniofull can you show an example of what you mean please?

It is probably not worth using a function, but maybe more DRY like using custom properties (or sass variable)
```CSS
--border-radius: 8px 0 0 8px;
--large: 24px;
--small: 4px;
```

**Comment by antoniofull** [comment]
Anyway is more a NIT comment tbh

**Review by scarciofolomarco — APPROVED** [review]

**Review by mrisoli — APPROVED** [review]

**Pull request merged**
