### PR TITLE
feat: Update eslint and add prettier

### PR DESCRIPTION
**Pull request by mathio**
Bump @typeform/eslint-config to 3.0.1

`yarn lint` also checks prettier formatting now. To format the project use your IDE or `yarn prettier`.

### CODE REVIEW

**Review by antoniofull — APPROVED** [review]

**Review by prilutskiy — COMMENTED** [review]
image
 😬

**Review by prilutskiy — APPROVED** [review]

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/17f2d6345b81a3516bf7562d98b2dc053fb8512b/embed.js

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/e903ce610c45bb41035404311063bc0ee2eb19ca/embed.js

**Comment by travis-tf** [comment]
*[BOT]* Preview available: https://embed.typeform.com/f843b57fa6ff68f65e3623c56bf6ed555da48c80/embed.js

**Pull request merged**
