### PR TITLE
feat(REACH-577): Add new options for sidetab

### LINKED ISSUE #586: Customize Text colour and Button size - Typeform user feedback (Sidetab)
I am implementing Typeform user feedback (Sidetab) in React using @typeform/embed-react library as following:

//In React I use the bellow code

<Sidetab
        id={formId}
        hidden={{
          user_id : me.id,
          name: me.first_name,
        }}
        ref={sidetabRef}
        medium="demo-test"
        buttonText="Send us feedback"
        buttonColor="#ffa366"
/>
All looks good so far, the only issue is that I have not found a way to change text colour in Button or the button size. It seems there is no fields/props in Sidetab component to change button text colour/font and button size.

### PR DESCRIPTION
**Pull request by mathio**
New customization options (for sidetab only):
- buttonTextColor
- buttonTextSize
- buttonWidth
- buttonHeight
- buttonAlign: align button relative to iframe (top / center / bottom)
- top: position iframe from top
- bottom: position iframe from bottom (when top is not provided)

| before (no customization) | after (fully customized) |
|---|---|
| Screenshot 2023-10-13 at 07 50 31 | Screenshot 2023-10-13 at 07 50 14 |

Merge #619 first.

Resolves #586

### CODE REVIEW

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `3eac84d7f5524e5ab240fb919e9dde997b565249` [here](https://embed.typeform.com/3eac84d7f5524e5ab240fb919e9dde997b565249/embed.js).

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `53868e862c56240054aa0e4da8bb642f897e6276` [here](https://embed.typeform.com/53868e862c56240054aa0e4da8bb642f897e6276/embed.js).

**Review by mumpo — APPROVED** [review]
It's a bit confusing that `buttonWidth` and `buttonHeight` apply **before** rotation, so you end up seeing an increase of `buttonHeight` as an increase of the button width. 

But I guess it would be confusing the other way around too...

**Comment by mathio** [comment]
> It's a bit confusing that `buttonWidth` and `buttonHeight` apply **before** rotation

Is there any better naming we can do? 🤔

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `8729daa75d6f1263722f5a891f6f12b692226311` [here](https://embed.typeform.com/8729daa75d6f1263722f5a891f6f12b692226311/embed.js).

**Pull request merged**
