### PR TITLE
feat(RESP-1747): removed chat ui capabilities

### PR DESCRIPTION
**Pull request by robespmun**

### CODE REVIEW

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `adb97bd1b61419ab605bee8e7b5210a760266cad` [here](https://embed.typeform.com/adb97bd1b61419ab605bee8e7b5210a760266cad/embed.js).

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `90c829fd0f904db7fb623baedf78e2457ec7e096` [here](https://embed.typeform.com/90c829fd0f904db7fb623baedf78e2457ec7e096/embed.js).

**Review by PabloMDiez — APPROVED** [review]

**Comment by mathio** [comment]
LGTM. Let me know when you want this merged 👍

**Review by mattrobinson10 — APPROVED** [review]

**Comment by robespmun** [comment]
Closing in favour of https://github.com/Typeform/embed/pull/580. Splitting the docs & implementation removal in two.

**Pull request closed without merging**
