### PR TITLE
fix(REACH-573): Update types of payloads for callbacks

### LINKED ISSUE #577: Incorrect Typeform types for onSubmit
Are the the typescript types wrong here?

https://github.com/Typeform/embed/blob/e58cd98e0086bd8c2fd6c602875472b8d52fbe94/packages/embed/src/base/actionable-options.ts#L6-L12

The JSDoc states a payload with only a `responseId` but on the documentation site it states you will get `responseId` and `formId` - see https://www.typeform.com/developers/embed/callbacks/#on-submit

```typescript
createPopup('<form-id>', {
  onSubmit: ({ formId, responseId }) => {
    console.log(`Form ${formId} submitted, response id: ${responseId}`)
  },
})
```

In VSCode the TypeScript intellisense overlay also suggests you will only get the `responseId`

image

Upon my testing, this is clearly not the case as I get the below from the props when the `onSubmit` is called

```javascript
{
  response_id: 'gzpqhq1so2obvheegzpqhieczjbh82qm', 
  responseId: 'gzpqhq1so2obvheegzpqhieczjbh82qm', 
  formId: 'MmvHZJQV'
}
```

### PR DESCRIPTION
**Pull request by mathio**
Match types defined in this lib with actual payload sent by the embedded form.

Resolves #577.

### CODE REVIEW

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `994680873fff1f7e3e1fd3988866b23a9b37f9ac` [here](https://embed.typeform.com/994680873fff1f7e3e1fd3988866b23a9b37f9ac/embed.js).

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `872c7b435f9373bc2d5797fb3e7d3c6088571d5b` [here](https://embed.typeform.com/872c7b435f9373bc2d5797fb3e7d3c6088571d5b/embed.js).

**Review by mumpo — APPROVED** [review]

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `12c8c72d0e9f4bbecaca6d7fa636e80311545959` [here](https://embed.typeform.com/12c8c72d0e9f4bbecaca6d7fa636e80311545959/embed.js).

**Pull request merged**
