### PR TITLE
chore(DIST-1898): Deploy PRs to AWS with hash

### PR DESCRIPTION
**Pull request by mathio**
Wait for approval on https://github.com/Typeform/typortal-chrome-extension/pull/33

### CODE REVIEW

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available, append `?embedVersion=279dfa78ea99f189ed0fb06d1100d9fd338d7fca` to a form url to check it out.

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `d83d5a492d74530eb0f0c6c8cb8fa39a42201385` [here](https://embed.typeform.com/d83d5a492d74530eb0f0c6c8cb8fa39a42201385/embed.js).

**Review by scarciofolomarco — APPROVED** [review]

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `85949975180e406d198cfc5620db51e9831501b5` [here](https://embed.typeform.com/85949975180e406d198cfc5620db51e9831501b5/embed.js).

**Pull request merged**
