### PR TITLE
feat(RESP-1781): Remove support for CUI

### PR DESCRIPTION
**Pull request by robespmun**
We're removing the capabilities to set up Chat (aka Conversations) UI embeds, since this feature is not supported anymore.

---

**BREAKING CHANGE:** CUI is not supported anymore

### CODE REVIEW

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `f6ab4b969bdb9791c785b8b0f86b6b6f59bb3628` [here](https://embed.typeform.com/f6ab4b969bdb9791c785b8b0f86b6b6f59bb3628/embed.js).

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `2968ee4adaa7fa758872c5461e94b9f265fb089d` [here](https://embed.typeform.com/2968ee4adaa7fa758872c5461e94b9f265fb089d/embed.js).

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `3f8245d4f7c4ce5afabc28a08cb00d421ed41c8b` [here](https://embed.typeform.com/3f8245d4f7c4ce5afabc28a08cb00d421ed41c8b/embed.js).

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `5c5600cb150da20ad002fbb5c3bd0151d0ad90a1` [here](https://embed.typeform.com/5c5600cb150da20ad002fbb5c3bd0151d0ad90a1/embed.js).

**Comment by typeform-ops-gha** [comment]
*[BOT]* Preview available with hash `81c52cdaeb9dcb26ad7fa0d66416d82e6d061f8d` [here](https://embed.typeform.com/81c52cdaeb9dcb26ad7fa0d66416d82e6d061f8d/embed.js).

**Review by mathio — APPROVED** [review]

**Pull request merged**
